TOPIC_KEYWORDS = {
    "Infrastruktur": [
        "jalan",
        "jembatan",
        "lampu",
        "drainase",
        "irigasi",
        "selokan",
        "air",
        "bersih",
        "sampah",
        "banjir",
        "pembangunan",
        "perbaikan",
        "rusak",
        "fasilitas",
        "akses",
    ],
    "Pelayanan Publik": [
        "pelayanan",
        "surat",
        "administrasi",
        "kartu",
        "ktp",
        "kk",
        "rt",
        "rw",
        "kantor desa",
        "proses",
        "lama",
    ],
    "Kesehatan": [
        "kesehatan",
        "puskesmas",
        "obat",
        "posyandu",
        "bidan",
        "vaksin",
        "gizi",
        "stunting",
        "rumah sakit",
    ],
    "Pendidikan": [
        "sekolah",
        "pendidikan",
        "guru",
        "siswa",
        "kelas",
        "buku",
        "beasiswa",
        "belajar",
        "madrasah",
    ],
    "Ekonomi": [
        "ekonomi",
        "usaha",
        "umkm",
        "pasar",
        "lapangan kerja",
        "kerja",
        "pendapatan",
        "harga",
        "modal",
    ],
    "Keamanan": [
        "keamanan",
        "kriminal",
        "maling",
        "pencurian",
        "preman",
        "banjir",
        "gelap",
        "jalan gelap",
        "rawan",
    ],
    "Lingkungan": [
        "lingkungan",
        "sampah",
        "bau",
        "pencemaran",
        "air kotor",
        "kumuh",
        "bersih",
        "hijau",
        "limbah",
    ],
    "Sosial": [
        "bantuan",
        "warga",
        "keluarga",
        "musyawarah",
        "program",
        "bansos",
        "gotong royong",
        "ibu",
        "anak",
    ],
}

TOPIC_PROFILES = {
    "Infrastruktur": (
        "Kerusakan jalan, jembatan, lampu penerangan, drainase, irigasi, akses air bersih, "
        "sampah, banjir, perbaikan fasilitas, dan pembangunan fisik desa."
    ),
    "Pelayanan Publik": (
        "Layanan administrasi desa, surat menyurat, proses dokumen, KTP, KK, kantor desa, "
        "kecepatan pelayanan, dan kualitas petugas layanan."
    ),
    "Kesehatan": (
        "Layanan puskesmas, posyandu, obat, bidan, vaksin, gizi, stunting, dan akses kesehatan warga."
    ),
    "Pendidikan": (
        "Sekolah, guru, siswa, kelas, buku, beasiswa, bantuan belajar, dan fasilitas pendidikan."
    ),
    "Ekonomi": (
        "Usaha, UMKM, pasar, lapangan kerja, pendapatan warga, harga kebutuhan, modal, dan aktivitas ekonomi desa."
    ),
    "Keamanan": (
        "Keamanan lingkungan, kriminalitas, pencurian, jalan gelap, wilayah rawan, dan kenyamanan malam hari."
    ),
    "Lingkungan": (
        "Kebersihan lingkungan, sampah, bau, pencemaran, air kotor, limbah, dan kondisi permukiman."
    ),
    "Sosial": (
        "Bantuan sosial, gotong royong, keluarga, musyawarah, program warga, dan persoalan sosial masyarakat."
    ),
}

POSITIVE_WORDS = {
    "baik",
    "bagus",
    "aman",
    "cepat",
    "mudah",
    "puas",
    "terima kasih",
    "ramah",
    "bersih",
    "lancar",
    "positif",
    "membantu",
    "teratur",
}

NEGATIVE_WORDS = {
    "buruk",
    "lambat",
    "parah",
    "rusak",
    "kotor",
    "sulit",
    "keluhan",
    "masalah",
    "tidak",
    "belum",
    "lama",
    "mahal",
    "gelap",
    "darurat",
    "anjlok",
    "macet",
    "bocor",
    "mati",
    "minim",
    "kurang",
}

NEGATION_WORDS = {
    "tidak",
    "bukan",
    "belum",
    "jangan",
    "kurang",
    "tanpa",
}

URGENT_WORDS = {
    "segera",
    "darurat",
    "mendesak",
    "parah",
    "berat",
    "kritikal",
    "sering",
    "sudah lama",
    "berbahaya",
    "mati",
    "bocor",
    "banjir",
    "longsor",
    "rusak berat",
}

STOPWORDS = {
    "yang",
    "dan",
    "di",
    "ke",
    "dari",
    "untuk",
    "pada",
    "dengan",
    "ini",
    "itu",
    "sebagai",
    "karena",
    "agar",
    "supaya",
    "tidak",
    "sudah",
    "belum",
    "akan",
    "ada",
    "dalam",
    "kami",
    "kita",
    "mereka",
    "saya",
    "aku",
    "anda",
    "warga",
    "desa",
    "rt",
    "rw",
    "nya",
    "lah",
    "pun",
    "atau",
    "juga",
    "bisa",
    "harus",
    "lebih",
    "sangat",
    "agar",
    "oleh",
    "saat",
    "sejak",
    "setelah",
    "sebelum",
    "lagi",
    "masih",
    "bagi",
    "tanpa",
    "dapat",
    "tersebut",
    "pihak",
    "mohon",
    "tolong",
}
